version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    environment:
      - MONGO_INITDB_DATABASE=wish
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local